### PR TITLE
you have been linted (added ESLint config w/ Angular plugin)

### PR DESCRIPTION
**Pull request by mbullington**

### CODE REVIEW

**Comment by rsquared226** [comment]
eslintfriendship

**Comment by stan29308** [comment]
Just a heads up, it might be beneficial to keep the semicolons based on [these](https://stackoverflow.com/questions/444080/do-you-recommend-using-semicolons-after-every-statement-in-javascript?noredirect=1&lq=1) [three](https://stackoverflow.com/questions/2399935/why-use-semicolon?noredirect=1&lq=1) [questions](https://stackoverflow.com/questions/4002234/do-we-need-semicolon-at-the-end?noredirect=1&lq=1)

**Comment by rsquared226** [comment]
@mbullington could you add that to the prettier config, I can go through the files themselves and format them after

**Comment by mbullington** [comment]
done @rsquared226

**Pull request merged**
