### PR TITLE
Delete it all

### PR DESCRIPTION
**Pull request by jmm8046**

### CODE REVIEW

**Review by rsquared226 — CHANGES_REQUESTED** [review]
Saketh will never forgive you

**Review by stan29308 — APPROVED** [review]

**Review by PScottZero — COMMENTED** [review]
Switch code to Fortran

**Review by PScottZero — COMMENTED** [review]
Must be approved by Yanling first

**Review by rsquared226 — CHANGES_REQUESTED** [review]
Julia please

**Pull request closed without merging**
